services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    image: fahad1000mir/nowlii-backend:dev
    container_name: nowlii-backend
    ports:
      - "8000:8000"
    volumes:
      - static_volume:/app/staticfiles
      - media_volume:/app/media
      - db_data:/app/database
    env_file:
      - .env
    environment:
      - DEBUG=False
      - DB_NAME=/app/database/db.sqlite3
    restart: always

volumes:
  db_data:
  static_volume:
  media_volume:

